from abc import ABC, abstractmethod
from typing import List, Optional
from datetime import date
from app.menu.domain.menu_day import MenuDay

class MenuDayRepository(ABC):
    @abstractmethod
    async def bulk_replace(self, menu_id: str, days: List[MenuDay]) -> None: ...
    @abstractmethod
    async def list_by_menu(self, menu_id: str) -> List[MenuDay]: ...
    @abstractmethod
    async def find_by_menu_and_date(self, menu_id: str, day: date) -> Optional[MenuDay]: ...
    @abstractmethod
    async def save(self, day: MenuDay) -> MenuDay: ...
    @abstractmethod
    async def find_by_id(self, menu_day_id: str) -> Optional[MenuDay]: ...
